# More option see https://github.com/DreamMaoMao/mango/wiki/

source=~/.config/mango/modules/autostart.conf
source=~/.config/mango/modules/appearance.conf
source=~/.config/mango/modules/binds.conf
source=~/.config/mango/noctalia.conf
source=~/.config/mango/modules/env.conf
source=~/.config/mango/modules/monitors.conf
source=~/.config/mango/modules/windoweffects.conf
source=~/.config/mango/modules/animations.conf
source=~/.config/mango/modules/inputs.conf
source=~/.config/mango/modules/misc.conf
source=~/.config/mango/modules/layout.conf
source=~/.config/mango/modules/overview.conf
