# Noctalia Theme for Mango
# Generated automatically by Noctalia Shell

shadowscolor = 0x000000ff
rootcolor = 0x0e1513ff
bordercolor = 0x89938fff
dropcolor = 0x84d6c280
splitcolor = 0xabcbe4ff
focuscolor = 0x84d6c2ff
maximizescreencolor = 0xb1ccc4ff
urgentcolor = 0xffb4abff
scratchpadcolor = 0xabcbe4ff
globalcolor = 0x005144ff
overlaycolor = 0x334b45ff
